### PR TITLE
feature: added bootstrap, removed unused files

### PR DESCRIPTION
**Pull request by omurbekjk**

### CODE REVIEW

**Comment by gaurav-gogia** [comment]
Thanks for adding bootstrap ^.^

**Comment by gaurav-gogia** [comment]
breaks splash screen functionality .-.

**Comment by omurbekjk** [comment]
@gaurav-gogia It is working fine in my environment. How did you launch it?

**Comment by gaurav-gogia** [comment]
I had to migrate code from 1.9 to 1.12 then I launched it by simply using `go run .` in app engine and now for some reason I'm unable to deploy on google app engine (its asking money for cloud builds) .-.

**Comment by omurbekjk** [comment]
funny though :)

**Pull request merged**
